In [2]:
from typing import List, Tuple
from helper_class import MixtureMeta
import pandas as pd
from pathlib import Path
import os
import librosa
import numpy as np
from faster_whisper import WhisperModel

/home/jamin/mambaforge/envs/fw311/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
def load_mixture_meta(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)

In [4]:
metas = load_mixture_meta(Path(os.pardir, Path("Output", "manifest.csv")))

In [ ]:
# extract row whose transcript contains ("any speaker", None) or ("any speaker", "None") or ("any speaker", np.nan) where transcript is a list of tuples (speaker, transcript)
row_none = metas[metas["transcript"].apply(lambda x: any((t[0] == "any speaker" and (t[1] is None or t[1] == "None" or (isinstance(t[1], float) and np.isnan(t[1]))) for t in eval(x))))]

In [7]:
row_none

Empty DataFrame
Columns: [clip_id, audio_path, transcript, overlap_ratio_target, overlap_ratio_actual, max_speakers, snr_db, noise_type, overlap_mask_path, source_files, noise_files]
Index: []

In [2]:
import os
print(os.environ.get("LD_LIBRARY_PATH"))

/home/jamin/mambaforge/envs/fw311/lib/python3.11/site-packages/nvidia/cublas/lib:/home/jamin/mambaforge/envs/fw311/lib/python3.11/site-packages/nvidia/cudnn/lib:

In [3]:
import ctypes
ctypes.CDLL("libcublas.so.12")
ctypes.CDLL("libcudnn.so.9")
print("CUDA libs load OK")

CUDA libs load OK

In [4]:
def load_mixture_meta(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)
def load_mixture_audio(path: Path, sr: int = 16000) -> Tuple[np.ndarray, int]:
    audio, sr = librosa.load(path, sr=sr)
    return audio, sr

In [5]:
meta_df = load_mixture_meta(Path(os.pardir,"Output", "manifest.csv"))

In [6]:
meta_df.clip_id.filter

<bound method NDFrame.filter of 0       mix_0.00_2_None_D_0000000
1       mix_0.00_2_None_P_0000001
2       mix_0.00_2_None_T_0000002
3        mix_0.00_2_7.4_D_0000003
4        mix_0.00_2_7.4_P_0000004
                  ...
3715       mix_0.40_2_0_P_0003715
3716       mix_0.40_2_0_T_0003716
3717      mix_0.40_2_-5_D_0003717
3718      mix_0.40_2_-5_P_0003718
3719      mix_0.40_2_-5_T_0003719
Name: clip_id, Length: 3720, dtype: str>

In [7]:
# filter out clip ids that starts with mix_0.14
test_meta = meta_df[meta_df.clip_id.str.startswith("mix_0.14_2_None_D_0000144")].head(1)
test_meta

,clip_id,audio_path,transcript,overlap_ratio_target,overlap_ratio_actual,max_speakers,snr_db,noise_type,overlap_mask_path,source_files,noise_files
144,mix_0.14_2_None_D_0000144,Output/audio/mix_0.14_2_None_D_0000144.wav,"[('125-121342-0038', ""THEY DON'T THEY JUST WAN...",0.14,0.14,2,NaN,D,Output/masks/mix_0.14_2_None_D_0000144.npy,[PosixPath('/home/jamin/Year3Proj/Data/LibriSp...,[]

In [8]:
print(test_meta.audio_path.values[0])
print(Path(os.pardir, test_meta.audio_path.values[0]))

Output/audio/mix_0.14_2_None_D_0000144.wav
../Output/audio/mix_0.14_2_None_D_0000144.wav

In [9]:
# model = WhisperModel("large-v3", device="cuda")

# segments, info = model.transcribe(Path(os.pardir, test_meta.audio_path.values[0]))
# for segment in segments:
#     print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))

In [10]:
# import torch
# from transformers import pipeline

# device = 0 if torch.cuda.is_available() else -1

# asr = pipeline(
#     "automatic-speech-recognition",
#     model="facebook/wav2vec2-large-960h",
#     device=0,
# )
# audio = load_mixture_audio(Path(os.pardir, test_meta.audio_path.values[0]))[0]
# result = asr(audio)
# print(result["text"])

In [11]:
# from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
# import torch

# # load model and processor
# processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-large-960h")
# model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-large-960h")
    
# # load dummy dataset and read soundfiles
# audio = load_mixture_audio(Path(os.pardir, test_meta.audio_path.values[0]))[0]

# # tokenize
# input_values = processor(audio, return_tensors="pt", padding="longest").input_values  # Batch size 1

# # retrieve logits
# logits = model(input_values).logits

# # take argmax and decode
# predicted_ids = torch.argmax(logits, dim=-1)
# transcription = processor.batch_decode(predicted_ids)

In [12]:
# print(test_meta.transcript.values[0].astype(str))

# print(" ".join(seg[1] for seg in test_meta.transcript.values[0]))

In [13]:
# import nemo.collections.asr as nemo_asr
# asr_model = nemo_asr.models.ASRModel.from_pretrained(model_name="nvidia/parakeet-tdt-0.6b-v3")
# output = asr_model.transcribe([Path(os.pardir, test_meta.audio_path.values[0])])
# print(output[0].text)

In [14]:
# import whisperx
# device = "cuda"   # or "cpu"
# batch_size = 1
# compute_type = "int8"
# model = whisperx.load_model("large-v2", device, compute_type=compute_type)
# audio = whisperx.load_audio(Path(os.pardir) / test_meta.audio_path.values[0])

# result = model.transcribe(audio, batch_size=batch_size)

In [ ]:
# import nemo.collections.asr as nemo_asr
# asr_model = nemo_asr.models.ASRModel.from_pretrained("nvidia/parakeet-tdt-0.6b-v2")
# transcript = asr_model.transcribe([test_meta.audio_path.values[0]])

[NeMo W 2026-04-04 00:15:05 megatron_init:62] Megatron num_microbatches_calculator not found, using Apex version.
OneLogger: Setting error_handling_strategy to DISABLE_QUIETLY_AND_REPORT_METRIC_ERROR for rank (rank=0) with OneLogger disabled. To override: explicitly set error_handling_strategy parameter.
No exporters were provided. This means that no telemetry data will be collected.
Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [24]:
import pickle
with open("funasr_output.pkl", "rb") as f:
    funasr_output = pickle.load(f)

In [29]:
funasr_output[0][0]

{'key': 'rand_key_1t9EwL56nGisi',
 'text': "They don't. They just want the fun of eating it all over again. The matron doesn't want to repeat her own feelings, but she's just a part of the world. Again, Ventnor's rifle cracked. One of the colors of the world is down, another's down, more did he reproach himself for feelings that were bound to the horseman, but his sworn foot soldiers, a forest of shining planks above them, clearly to us came their battle cries. Again, Ventnor's rifle cracked. I detest poor people. I hate them for being poor. Poverty may have been beautiful for the horseman, but it's one foot in a forest and truly a big faint radiance. It was her eyes, her great wide eyes whose clear form magnified us. Over us whined the bullets from the covering guns. The fathom deeper by lie, with old desires restrained before. No, I heard a song. The matron doesn't want to repeat her. We just want to repeat her honeymoon. How the smell of it suddenly cleared the air and threw everyone in the residence. If we could but reach it, the darting snake streamed red.",
 'text_tn': 'They dont They just want the fun of eating it all over again The matron doesnt want to repeat her own feelings but shes just a part of the world Again Ventnors rifle cracked One of the colors of the world is down anothers down more did he reproach himself for feelings that were bound to the horseman but his sworn foot soldiers a forest of shining planks above them clearly to us came their battle cries Again Ventnors rifle cracked I detest poor people I hate them for being poor Poverty may have been beautiful for the horseman but its one foot in a forest and truly a big faint radiance It was her eyes her great wide eyes whose clear form magnified us Over us whined the bullets from the covering guns The fathom deeper by lie with old desires restrained before No I heard a song The matron doesnt want to repeat her We just want to repeat her honeymoon How the smell of it suddenly cleared the air and threw everyone in the residence If we could but reach it the darting snake streamed red',
 'label': 'null',
 'ctc_text': "they don't they just want the fun of eating it all over again the mat doesn't want to repeat her girlhood she wants to repeat her own tastes the best isabel cl ros el were all american would pitch probably south ros was out wonderful hit ever the first based from it and ever was swift than te at heels from length the dart red't over again the't't want to her girlfriendhood she wants to repeat her honeymoon how the smell of it has suddenly cleared the air and given everyone in the car a moment glow i poor people thought am suddenly i hate them for being poor poverty may have been beautiful the horse soldiers a forest of shining points and dul gleaming pe above them clearly to us came their battle cries again vent's rifle one of the foremost went down more he rep himself for feelings that were natural and and sincere he all his reactions as a part of himchangingoral this problem of poverty transformed magn over mine the close were to the fisher we couldn but close the arrows none more virtue to lose just as a cooling pot gives off heat so all through youth and ad we give off of virtue that's what's called genius mis interesting idea flames no nor that through her ve her body gle faint rad it was her eyes her great wide eyes whose clear depths were like pools lie oldrainedined to clam lifeward with a cry as dark flies out the grain door and so in quest of cre to share i seek assert day again",
 'ctc_timestamps': [{'token': 'they',
   'start_time': 0.24,
   'end_time': 0.3,
   'score': 0.45},
  {'token': ' don', 'start_time': 0.42, 'end_time': 0.48, 'score': 0.729},
  {'token': "'t", 'start_time': 0.54, 'end_time': 0.66, 'score': 0.781},
  {'token': ' they', 'start_time': 1.2, 'end_time': 1.26, 'score': 0.862},
  {'token': ' just', 'start_time': 1.44, 'end_time': 1.5, 'score': 0.98},
  {'token': ' want', 'start_time': 1.62, 'end_time': 1.68, 'score': 0.973},
  {'token': ' the', 'start_time': 1.8, 'end_time': 1.86, 'score': 0.888},
  {'token': ' fun', 'start_time': 1.86, 'end_time': 1.98, 'score': 0.799},
  {'token': ' of', 'start_time': 2.04, 'end_time': 2.1, 'score': 0.977},
  {'token': ' eating', 'start_time': 2.22, 'end_time': 2.28, 'score': 0.977},
  {'token': ' it', 'start_time': 2.46, 'end_time': 2.52, 'score': 0.961},
  {'token': ' all', 'start_time': 2.64, 'end_time': 2.7, 'score': 0.996},
  {'token': ' over', 'start_time': 2.82, 'end_time': 2.88, 'score': 0.991},
  {'token': ' again', 'start_time': 3.18, 'end_time': 3.24, 'score': 0.983},
  {'token': ' the', 'start_time': 4.26, 'end_time': 4.32, 'score': 0.907},
  {'token': ' mat', 'start_time': 4.38, 'end_time': 4.44, 'score': 0.215},
  {'token': ' doesn', 'start_time': 4.8, 'end_time': 4.86, 'score': 0.828},
  {'token': "'t", 'start_time': 4.86, 'end_time': 4.98, 'score': 0.955},
  {'token': ' want', 'start_time': 5.1, 'end_time': 5.16, 'score': 0.647},
  {'token': ' to', 'start_time': 5.22, 'end_time': 5.28, 'score': 0.917},
  {'token': ' repeat', 'start_time': 5.4, 'end_time': 5.52, 'score': 0.914},
  {'token': ' her', 'start_time': 5.7, 'end_time': 5.76, 'score': 0.996},
  {'token': ' girl', 'start_time': 5.82, 'end_time': 5.88, 'score': 0.688},
  {'token': 'hood', 'start_time': 6.12, 'end_time': 6.18, 'score': 0.791},
  {'token': ' she', 'start_time': 6.72, 'end_time': 6.78, 'score': 0.836},
  {'token': ' wants', 'start_time': 6.9, 'end_time': 6.96, 'score': 0.985},
  {'token': ' to', 'start_time': 7.08, 'end_time': 7.14, 'score': 0.956},
  {'token': ' repeat', 'start_time': 7.26, 'end_time': 7.38, 'score': 0.84},
  {'token': ' her', 'start_time': 7.56, 'end_time': 7.62, 'score': 0.994},
  {'token': ' own', 'start_time': 9.36, 'end_time': 9.42, 'score': 0.59},
  {'token': ' tastes', 'start_time': 9.66, 'end_time': 9.72, 'score': 0.296},
  {'token': ' the', 'start_time': 9.96, 'end_time': 10.02, 'score': 0.776},
  {'token': ' best', 'start_time': 10.14, 'end_time': 10.2, 'score': 0.781},
  {'token': ' is', 'start_time': 10.74, 'end_time': 10.8, 'score': 0.412},
  {'token': 'abel', 'start_time': 10.98, 'end_time': 11.04, 'score': 0.71},
  {'token': ' cl', 'start_time': 11.4, 'end_time': 11.46, 'score': 0.611},
  {'token': ' ros', 'start_time': 12.0, 'end_time': 12.06, 'score': 0.622},
  {'token': ' el', 'start_time': 12.6, 'end_time': 12.66, 'score': 0.47},
  {'token': ' were', 'start_time': 13.2, 'end_time': 13.26, 'score': 0.922},
  {'token': ' all', 'start_time': 13.44, 'end_time': 13.5, 'score': 0.864},
  {'token': ' american',
   'start_time': 13.74,
   'end_time': 13.8,
   'score': 0.565},
  {'token': ' would', 'start_time': 15.42, 'end_time': 15.48, 'score': 0.562},
  {'token': ' pitch', 'start_time': 15.6, 'end_time': 15.66, 'score': 0.792},
  {'token': ' probably',
   'start_time': 15.9,
   'end_time': 15.96,
   'score': 0.884},
  {'token': ' south', 'start_time': 16.38, 'end_time': 16.44, 'score': 0.986},
  {'token': ' ros', 'start_time': 17.46, 'end_time': 17.52, 'score': 0.735},
  {'token': ' was', 'start_time': 17.94, 'end_time': 18.0, 'score': 0.931},
  {'token': ' out', 'start_time': 18.18, 'end_time': 18.24, 'score': 0.982},
  {'token': ' wonderful',
   'start_time': 18.9,
   'end_time': 18.96,
   'score': 0.467},
  {'token': ' hit', 'start_time': 19.38, 'end_time': 19.44, 'score': 0.9},
  {'token': ' ever', 'start_time': 19.86, 'end_time': 19.92, 'score': 0.825},
  {'token': ' the', 'start_time': 20.16, 'end_time': 20.22, 'score': 0.749},
  {'token': ' first', 'start_time': 20.7, 'end_time': 20.76, 'score': 0.727},
  {'token': ' based', 'start_time': 21.0, 'end_time': 21.06, 'score': 0.394},
  {'token': ' from', 'start_time': 21.54, 'end_time': 21.6, 'score': 0.812},
  {'token': ' it', 'start_time': 21.72, 'end_time': 21.78, 'score': 0.646},
  {'token': ' and', 'start_time': 22.44, 'end_time': 22.56, 'score': 0.765},
  {'token': ' ever', 'start_time': 22.68, 'end_time': 22.74, 'score': 0.804},
  {'token': ' was', 'start_time': 23.04, 'end_time': 23.1, 'score': 0.555},
  {'token': ' swift', 'start_time': 23.4, 'end_time': 23.46, 'score': 0.587},
  {'token': ' than', 'start_time': 23.76, 'end_time': 23.82, 'score': 0.555},
  {'token': ' te', 'start_time': 24.6, 'end_time': 24.66, 'score': 0.683},
  {'token': ' at', 'start_time': 25.08, 'end_time': 25.14, 'score': 0.51},
  {'token': ' heels', 'start_time': 25.44, 'end_time': 25.5, 'score': 0.637},
  {'token': ' from', 'start_time': 28.02, 'end_time': 28.08, 'score': 0.523},
  {'token': ' length', 'start_time': 28.8, 'end_time': 28.86, 'score': 0.64},
  {'token': ' the', 'start_time': 29.22, 'end_time': 29.28, 'score': 0.67},
  {'token': ' dart', 'start_time': 29.46, 'end_time': 29.52, 'score': 0.848},
  {'token': ' red', 'start_time': 30.96, 'end_time': 31.02, 'score': 0.598},
  {'token': "'t", 'start_time': 32.4, 'end_time': 32.46, 'score': 0.67},
  {'token': ' over', 'start_time': 34.74, 'end_time': 34.8, 'score': 0.564},
  {'token': ' again', 'start_time': 35.1, 'end_time': 35.16, 'score': 0.568},
  {'token': ' the', 'start_time': 36.18, 'end_time': 36.24, 'score': 0.558},
  {'token': "'t", 'start_time': 36.66, 'end_time': 36.72, 'score': 0.302},
  {'token': "'t", 'start_time': 36.78, 'end_time': 36.84, 'score': 0.836},
  {'token': ' want', 'start_time': 36.96, 'end_time': 37.02, 'score': 0.468},
  {'token': ' to', 'start_time': 37.14, 'end_time': 37.2, 'score': 0.629},
  {'token': ' her', 'start_time': 37.62, 'end_time': 37.68, 'score': 0.99},
  {'token': ' girlfriend',
   'start_time': 37.74,
   'end_time': 37.8,
   'score': 0.477},
  {'token': 'hood', 'start_time': 38.04, 'end_time': 38.1, 'score': 0.716},
  {'token': ' she', 'start_time': 38.64, 'end_time': 38.7, 'score': 0.694},
  {'token': ' wants', 'start_time': 38.76, 'end_time': 38.82, 'score': 0.95},
  {'token': ' to', 'start_time': 39.0, 'end_time': 39.06, 'score': 0.852},
  {'token': ' repeat', 'start_time': 39.18, 'end_time': 39.24, 'score': 0.955},
  {'token': ' her', 'start_time': 39.48, 'end_time': 39.54, 'score': 0.996},
  {'token': ' honeymoon',
   'start_time': 39.6,
   'end_time': 39.72,
   'score': 0.812},
  {'token': ' how', 'start_time': 40.62, 'end_time': 40.68, 'score': 0.98},
  {'token': ' the', 'start_time': 40.86, 'end_time': 40.92, 'score': 0.979},
  {'token': ' smell', 'start_time': 41.04, 'end_time': 41.1, 'score': 0.986},
  {'token': ' of', 'start_time': 41.22, 'end_time': 41.28, 'score': 0.819},
  {'token': ' it', 'start_time': 41.34, 'end_time': 41.4, 'score': 0.975},
  {'token': ' has', 'start_time': 41.58, 'end_time': 41.64, 'score': 0.516},
  {'token': ' suddenly',
   'start_time': 41.82,
   'end_time': 41.88,
   'score': 0.82},
  {'token': ' cleared', 'start_time': 42.3, 'end_time': 42.36, 'score': 0.96},
  {'token': ' the', 'start_time': 42.6, 'end_time': 42.66, 'score': 0.721},
  {'token': ' air', 'start_time': 42.72, 'end_time': 42.84, 'score': 0.897},
  {'token': ' and', 'start_time': 42.96, 'end_time': 43.02, 'score': 0.951},
  {'token': ' given', 'start_time': 43.14, 'end_time': 43.2, 'score': 0.682},
  {'token': ' everyone',
   'start_time': 43.5,
   'end_time': 43.56,
   'score': 0.936},
  {'token': ' in', 'start_time': 43.8, 'end_time': 43.86, 'score': 0.87},
  {'token': ' the', 'start_time': 43.92, 'end_time': 43.98, 'score': 0.813},
  {'token': ' car', 'start_time': 44.1, 'end_time': 44.16, 'score': 0.968},
  {'token': ' a', 'start_time': 44.52, 'end_time': 44.58, 'score': 0.731},
  {'token': ' moment', 'start_time': 44.7, 'end_time': 44.76, 'score': 0.62},
  {'token': ' glow', 'start_time': 45.36, 'end_time': 45.42, 'score': 0.797},
  {'token': ' i', 'start_time': 46.86, 'end_time': 46.92, 'score': 0.896},
  {'token': ' poor', 'start_time': 47.58, 'end_time': 47.7, 'score': 0.937},
  {'token': ' people', 'start_time': 47.82, 'end_time': 47.94, 'score': 0.994},
  {'token': ' thought',
   'start_time': 48.36,
   'end_time': 48.42,
   'score': 0.818},
  {'token': ' am', 'start_time': 48.6, 'end_time': 48.66, 'score': 0.68},
  {'token': ' suddenly',
   'start_time': 49.08,
   'end_time': 49.14,
   'score': 0.608},
  {'token': ' i', 'start_time': 50.1, 'end_time': 50.16, 'score': 0.903},
  {'token': ' hate', 'start_time': 50.28, 'end_time': 50.34, 'score': 0.943},
  {'token': ' them', 'start_time': 50.52, 'end_time': 50.58, 'score': 0.851},
  {'token': ' for', 'start_time': 50.7, 'end_time': 50.76, 'score': 0.78},
  {'token': ' being', 'start_time': 50.82, 'end_time': 50.88, 'score': 0.91},
  {'token': ' poor', 'start_time': 51.12, 'end_time': 51.18, 'score': 0.847},
  {'token': ' poverty',
   'start_time': 51.96,
   'end_time': 52.02,
   'score': 0.973},
  {'token': ' may', 'start_time': 52.44, 'end_time': 52.5, 'score': 0.972},
  {'token': ' have', 'start_time': 52.56, 'end_time': 52.62, 'score': 0.539},
  {'token': ' been', 'start_time': 52.74, 'end_time': 52.8, 'score': 0.937},
  {'token': ' beautiful',
   'start_time': 52.92,
   'end_time': 52.98,
   'score': 0.579},
  {'token': ' the', 'start_time': 53.46, 'end_time': 53.52, 'score': 0.596},
  {'token': ' horse', 'start_time': 53.58, 'end_time': 53.64, 'score': 0.487},
  {'token': ' soldiers',
   'start_time': 54.72,
   'end_time': 54.78,
   'score': 0.442},
  {'token': ' a', 'start_time': 55.2, 'end_time': 55.26, 'score': 0.449},
  {'token': ' forest', 'start_time': 55.32, 'end_time': 55.38, 'score': 0.732},
  {'token': ' of', 'start_time': 55.74, 'end_time': 55.8, 'score': 0.716},
  {'token': ' shining', 'start_time': 56.1, 'end_time': 56.16, 'score': 0.449},
  {'token': ' points', 'start_time': 56.52, 'end_time': 56.58, 'score': 0.699},
  {'token': ' and', 'start_time': 56.94, 'end_time': 57.0, 'score': 0.786},
  {'token': ' dul', 'start_time': 57.12, 'end_time': 57.18, 'score': 0.163},
  {'token': ' gle', 'start_time': 57.54, 'end_time': 57.6, 'score': 0.879},
  {'token': 'aming', 'start_time': 57.72, 'end_time': 57.78, 'score': 0.516},
  {'token': ' pe', 'start_time': 57.96, 'end_time': 58.02, 'score': 0.285},
  {'token': ' above', 'start_time': 58.32, 'end_time': 58.38, 'score': 0.947},
  {'token': ' them', 'start_time': 58.56, 'end_time': 58.62, 'score': 0.983},
  {'token': ' clearly',
   'start_time': 59.28,
   'end_time': 59.34,
   'score': 0.874},
  {'token': ' to', 'start_time': 59.76, 'end_time': 59.82, 'score': 0.851},
  {'token': ' us', 'start_time': 59.88, 'end_time': 59.94, 'score': 0.547},
  {'token': ' came', 'start_time': 60.18, 'end_time': 60.24, 'score': 0.909},
  {'token': ' their', 'start_time': 60.48, 'end_time': 60.54, 'score': 0.798},
  {'token': ' battle', 'start_time': 60.66, 'end_time': 60.72, 'score': 0.919},
  {'token': ' cries', 'start_time': 61.08, 'end_time': 61.14, 'score': 0.696},
  {'token': ' again', 'start_time': 62.4, 'end_time': 62.46, 'score': 0.975},
  {'token': ' vent', 'start_time': 62.76, 'end_time': 62.82, 'score': 0.54},
  {'token': "'s", 'start_time': 63.0, 'end_time': 63.12, 'score': 0.581},
  {'token': ' rifle', 'start_time': 63.24, 'end_time': 63.3, 'score': 0.794},
  {'token': ' one', 'start_time': 64.56, 'end_time': 64.62, 'score': 0.799},
  {'token': ' of', 'start_time': 64.68, 'end_time': 64.74, 'score': 0.762},
  {'token': ' the', 'start_time': 64.74, 'end_time': 64.8, 'score': 0.8},
  {'token': ' foremost',
   'start_time': 64.92,
   'end_time': 64.98,
   'score': 0.833},
  {'token': ' went', 'start_time': 65.88, 'end_time': 65.94, 'score': 0.704},
  {'token': ' down', 'start_time': 66.18, 'end_time': 66.24, 'score': 0.905},
  {'token': ' more', 'start_time': 67.56, 'end_time': 67.62, 'score': 0.364},
  {'token': ' he', 'start_time': 67.98, 'end_time': 68.04, 'score': 0.694},
  {'token': ' rep', 'start_time': 68.16, 'end_time': 68.22, 'score': 0.794},
  {'token': ' himself',
   'start_time': 68.58,
   'end_time': 68.64,
   'score': 0.893},
  {'token': ' for', 'start_time': 68.94, 'end_time': 69.0, 'score': 0.582},
  {'token': ' feelings',
   'start_time': 69.12,
   'end_time': 69.18,
   'score': 0.873},
  {'token': ' that', 'start_time': 69.48, 'end_time': 69.54, 'score': 0.964},
  {'token': ' were', 'start_time': 69.6, 'end_time': 69.72, 'score': 0.874},
  {'token': ' natural', 'start_time': 69.84, 'end_time': 69.9, 'score': 0.981},
  {'token': ' and', 'start_time': 70.2, 'end_time': 70.26, 'score': 0.975},
  {'token': ' and', 'start_time': 70.32, 'end_time': 70.38, 'score': 0.529},
  {'token': ' sincere',
   'start_time': 70.56,
   'end_time': 70.62,
   'score': 0.334},
  {'token': ' he', 'start_time': 71.64, 'end_time': 71.7, 'score': 0.904},
  {'token': ' all', 'start_time': 72.24, 'end_time': 72.3, 'score': 0.961},
  {'token': ' his', 'start_time': 72.42, 'end_time': 72.48, 'score': 0.968},
  {'token': ' reactions',
   'start_time': 72.66,
   'end_time': 72.72,
   'score': 0.659},
  {'token': ' as', 'start_time': 73.08, 'end_time': 73.14, 'score': 0.741},
  {'token': ' a', 'start_time': 73.26, 'end_time': 73.32, 'score': 0.864},
  {'token': ' part', 'start_time': 73.38, 'end_time': 73.44, 'score': 0.997},
  {'token': ' of', 'start_time': 73.56, 'end_time': 73.62, 'score': 0.896},
  {'token': ' him', 'start_time': 73.68, 'end_time': 73.74, 'score': 0.813},
  {'token': 'changing',
   'start_time': 74.28,
   'end_time': 74.34,
   'score': 0.596},
  {'token': 'oral', 'start_time': 75.12, 'end_time': 75.18, 'score': 0.547},
  {'token': ' this', 'start_time': 76.38, 'end_time': 76.44, 'score': 0.946},
  {'token': ' problem',
   'start_time': 76.68,
   'end_time': 76.74,
   'score': 0.979},
  {'token': ' of', 'start_time': 76.98, 'end_time': 77.04, 'score': 0.737},
  {'token': ' poverty',
   'start_time': 77.22,
   'end_time': 77.28,
   'score': 0.902},
  {'token': ' transformed',
   'start_time': 77.82,
   'end_time': 77.88,
   'score': 0.869},
  {'token': ' magn', 'start_time': 78.48, 'end_time': 78.54, 'score': 0.918},
  {'token': ' over', 'start_time': 79.02, 'end_time': 79.08, 'score': 0.714},
  {'token': ' mine', 'start_time': 79.44, 'end_time': 79.5, 'score': 0.203},
  {'token': ' the', 'start_time': 79.74, 'end_time': 79.8, 'score': 0.544},
  {'token': ' close', 'start_time': 81.96, 'end_time': 82.02, 'score': 0.474},
  {'token': ' were', 'start_time': 82.32, 'end_time': 82.38, 'score': 0.523},
  {'token': ' to', 'start_time': 82.92, 'end_time': 82.98, 'score': 0.678},
  {'token': ' the', 'start_time': 83.04, 'end_time': 83.1, 'score': 0.525},
  {'token': ' fisher', 'start_time': 83.58, 'end_time': 83.64, 'score': 0.659},
  {'token': ' we', 'start_time': 84.6, 'end_time': 84.66, 'score': 0.539},
  {'token': ' couldn', 'start_time': 84.72, 'end_time': 84.78, 'score': 0.397},
  {'token': ' but', 'start_time': 84.96, 'end_time': 85.02, 'score': 0.547},
  {'token': ' close', 'start_time': 85.92, 'end_time': 85.98, 'score': 0.386},
  {'token': ' the', 'start_time': 88.2, 'end_time': 88.26, 'score': 0.818},
  {'token': ' arrows', 'start_time': 88.32, 'end_time': 88.44, 'score': 0.668},
  {'token': ' none', 'start_time': 89.76, 'end_time': 89.82, 'score': 0.631},
  {'token': ' more', 'start_time': 91.02, 'end_time': 91.08, 'score': 0.717},
  {'token': ' virtue', 'start_time': 91.26, 'end_time': 91.32, 'score': 0.439},
  {'token': ' to', 'start_time': 91.56, 'end_time': 91.62, 'score': 0.746},
  {'token': ' lose', 'start_time': 91.74, 'end_time': 91.8, 'score': 0.861},
  {'token': ' just', 'start_time': 92.76, 'end_time': 92.88, 'score': 0.869},
  {'token': ' as', 'start_time': 93.0, 'end_time': 93.06, 'score': 0.798},
  {'token': ' a', 'start_time': 93.12, 'end_time': 93.18, 'score': 0.489},
  {'token': ' cooling', 'start_time': 93.24, 'end_time': 93.3, 'score': 0.903},
  {'token': ' pot', 'start_time': 93.54, 'end_time': 93.6, 'score': 0.814},
  {'token': ' gives', 'start_time': 93.84, 'end_time': 93.9, 'score': 0.818},
  {'token': ' off', 'start_time': 94.02, 'end_time': 94.08, 'score': 0.995},
  {'token': ' heat', 'start_time': 94.26, 'end_time': 94.32, 'score': 0.973},