In [3]:
from typing import List, Tuple
from helper_class import MixtureMeta
import pandas as pd
from pathlib import Path
import os
import librosa
import numpy as np
from faster_whisper import WhisperModel

/home/jamin/mambaforge/envs/fw311/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [18]:
faster_whiper_model = WhisperModel("large-v3", device="cuda", compute_type="int8")
segments, info = faster_whiper_model.transcribe(Path(os.pardir) / Path("Output/audio/mix_0001104_0.14_2_None_D.wav"))

In [ ]:
print(info)

TranscriptionInfo(language='en', language_probability=0.9892578125, duration=63.38775, duration_after_vad=63.38775, all_language_probs=[('en', 0.9892578125), ('cy', 0.006565093994140625), ('fr', 0.0004906654357910156), ('es', 0.0004229545593261719), ('pt', 0.0003819465637207031), ('de', 0.0003674030303955078), ('nn', 0.00022459030151367188), ('ru', 0.00021767616271972656), ('it', 0.00020611286163330078), ('la', 0.00019359588623046875), ('sv', 0.00018918514251708984), ('ja', 0.0001804828643798828), ('nl', 0.00014162063598632812), ('pl', 0.00011295080184936523), ('zh', 0.00011032819747924805), ('vi', 0.00010609626770019531), ('ko', 9.965896606445312e-05), ('tr', 7.176399230957031e-05), ('fi', 5.459785461425781e-05), ('ar', 4.601478576660156e-05), ('cs', 3.784894943237305e-05), ('da', 2.8789043426513672e-05), ('mi', 2.6226043701171875e-05), ('hi', 2.384185791015625e-05), ('no', 2.294778823852539e-05), ('hu', 1.8417835235595703e-05), ('id', 1.6927719116210938e-05), ('el', 1.6629695892333984e-05), ('ms', 1.3053417205810547e-05), ('km', 1.3053417205810547e-05), ('haw', 1.2159347534179688e-05), ('ca', 1.1801719665527344e-05), ('jw', 1.043081283569336e-05), ('ta', 9.953975677490234e-06), ('ro', 7.987022399902344e-06), ('ur', 6.198883056640625e-06), ('th', 5.364418029785156e-06), ('br', 4.708766937255859e-06), ('fa', 3.874301910400391e-06), ('si', 3.7550926208496094e-06), ('sn', 3.6954879760742188e-06), ('is', 3.5762786865234375e-06), ('ml', 3.3974647521972656e-06), ('sl', 2.9802322387695312e-06), ('tl', 2.9802322387695312e-06), ('bn', 2.5033950805664062e-06), ('uk', 2.2649765014648438e-06), ('gl', 1.7285346984863281e-06), ('he', 1.6689300537109375e-06), ('sw', 1.5497207641601562e-06), ('af', 1.0132789611816406e-06), ('lv', 9.5367431640625e-07), ('az', 9.5367431640625e-07), ('sk', 8.344650268554688e-07), ('sa', 8.344650268554688e-07), ('et', 8.344650268554688e-07), ('yo', 8.344650268554688e-07), ('te', 7.748603820800781e-07), ('bs', 7.748603820800781e-07), ('hr', 7.152557373046875e-07), ('pa', 4.76837158203125e-07), ('bg', 4.172325134277344e-07), ('eu', 4.172325134277344e-07), ('lt', 4.172325134277344e-07), ('yue', 3.5762786865234375e-07), ('sq', 2.384185791015625e-07), ('hy', 2.384185791015625e-07), ('my', 2.384185791015625e-07), ('ht', 2.384185791015625e-07), ('be', 1.7881393432617188e-07), ('ne', 1.7881393432617188e-07), ('mr', 1.1920928955078125e-07), ('fo', 1.1920928955078125e-07), ('sr', 5.960464477539063e-08), ('kn', 5.960464477539063e-08), ('bo', 5.960464477539063e-08), ('mt', 5.960464477539063e-08), ('mn', 5.960464477539063e-08), ('ps', 5.960464477539063e-08), ('yi', 5.960464477539063e-08), ('kk', 5.960464477539063e-08), ('sd', 5.960464477539063e-08), ('oc', 5.960464477539063e-08), ('so', 0.0), ('uz', 0.0), ('su', 0.0), ('ba', 0.0), ('ha', 0.0), ('ln', 0.0), ('mk', 0.0), ('tt', 0.0), ('as', 0.0), ('mg', 0.0), ('ka', 0.0), ('tg', 0.0), ('lb', 0.0), ('gu', 0.0), ('am', 0.0), ('tk', 0.0), ('lo', 0.0)], transcription_options=TranscriptionOptions(beam_size=5, best_of=5, patience=1, length_penalty=1, repetition_penalty=1, no_repeat_ngram_size=0, log_prob_threshold=-1.0, no_speech_threshold=0.6, compression_ratio_threshold=2.4, condition_on_previous_text=True, prompt_reset_on_temperature=0.5, temperatures=[0.0, 0.2, 0.4, 0.6, 0.8, 1.0], initial_prompt=None, prefix=None, suppress_blank=True, suppress_tokens=(1, 2, 7, 8, 9, 10, 14, 25, 26, 27, 28, 29, 31, 58, 59, 60, 61, 62, 63, 90, 91, 92, 93, 359, 503, 522, 542, 873, 893, 902, 918, 922, 931, 1350, 1853, 1982, 2460, 2627, 3246, 3253, 3268, 3536, 3846, 3961, 4183, 4667, 6585, 6647, 7273, 9061, 9383, 10428, 10929, 11938, 12033, 12331, 12562, 13793, 14157, 14635, 15265, 15618, 16553, 16604, 18362, 18956, 20075, 21675, 22520, 26130, 26161, 26435, 28279, 29464, 31650, 32302, 32470, 36865, 42863, 47425, 49870, 50254, 50258, 50359, 50360, 50361, 50362, 50363), without_timestamps=False, max_initial_timestamp=1.0, word_timestamps=False, prepend_punctuations='"\'“¿([{-', append_punctuations='"\'.。,，!！?？:：”)]}、', multilingual=False, max_new_tokens=None, clip_timestamps=[0.0], hallucination_silence_threshold=None, hotwords=None), vad_options=None)

TypeError: object of type 'Segment' has no len()

In [20]:
for segments in segments:
    print("start: {:.2f}s, end: {:.2f}s, text: {}".format(segments.start, segments.end, segments.text))

start: 0.00s, end: 2.72s, text:  While they went on holiday, we got the...
start: 2.72s, end: 5.74s, text:  They might be broken, but they are not defeated.
start: 7.04s, end: 10.02s, text:  Her condition was yesterday described as critical, but stable.
start: 10.02s, end: 11.36s, text:  His third goal was superb.
start: 12.62s, end: 14.70s, text:  This film will be totally awesome.
start: 16.32s, end: 19.26s, text:  I decided to tell a bit of the story about myself.
start: 19.78s, end: 21.10s, text:  I expect a rapid response.
start: 22.02s, end: 23.48s, text:  This is a national crisis.
start: 25.08s, end: 27.78s, text:  The figures are bad, but not that bad.
start: 27.78s, end: 30.62s, text:  It has all been arranged.
start: 30.62s, end: 33.32s, text:  Every time I play, I do not understand their reaction.
start: 35.18s, end: 37.16s, text:  It has moved on in the last week.
start: 39.74s, end: 41.98s, text:  Florida is a pivotal state in the nation.
start: 41.98s, end: 43.34s, text:  They should take their mobile phones.
start: 44.80s, end: 47.84s, text:  George W. Bush, the US President, condemned the attacks.
start: 48.98s, end: 50.42s, text:  They want to be entertained.
start: 51.30s, end: 52.92s, text:  I was in daily contact.
start: 54.48s, end: 57.04s, text:  Certainly, the Taliban regime is finished.
start: 57.78s, end: 60.16s, text:  No meaningful response was issued.
start: 61.24s, end: 62.48s, text:  It changed my life.

KeyboardInterrupt:

In [4]:
def load_mixture_meta(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)

In [5]:
metas = load_mixture_meta(Path(os.pardir, Path("Output", "manifest.csv")))

In [6]:
def _split_into_two_chains(segments: List[Tuple[str, str]]) -> Tuple[List[str], List[str]]:
    """Split speaker-labeled segments into two ordered word chains."""
    # turn a string of segments into a list of tuples (speaker, word)
    segments = eval(segments)
    # print(f"Segments: {segments}")
    speakers = set(seg[0] for seg in segments)
    # print(f"Speakers: {speakers}")
    first_speaker = list(speakers)[0]
    # print(f"First speaker: {first_speaker}")
    chain_a = " ".join([seg[1] for seg in segments if seg[0] == first_speaker]).lower()
    second_speaker = list(speakers)[1]
    # print(f"Second speaker: {second_speaker}")
    chain_b = " ".join([seg[1] for seg in segments if seg[0] == second_speaker]).lower()
    return chain_a, chain_b

In [7]:
from wer_evaluation import get_hypothesis_transcription, load_asr_transcriptions
from mrs_beam_wer import mrs_wer_beam_2chain
#get clip id mix_0002525_0.40_2_7.4_T
# get corresponding transcription of parakeet from ASR_transcriptions.json
meta_test = metas[metas["clip_id"] == "mix_0000101_0.00_2_7.4_T"].iloc[0]
print(meta_test)
ref = meta_test["transcript"]

asr_data = load_asr_transcriptions(Path(os.pardir, "ASR_transcriptions.json"))
hyp = get_hypothesis_transcription(asr_data, "mix_0002525_0.40_2_7.4_T", "parakeet")
print(hyp)
print(ref)
chain_a, chain_b = _split_into_two_chains(ref)
print(chain_a)
print(chain_b)

clip_id                                          mix_0000101_0.00_2_7.4_T
audio_path                      Output/audio/mix_0000101_0.00_2_7.4_T.wav
transcript              [('218', 'A LAMP COULD NOT HAVE EXPIRED WITH M...
overlap_ratio_target                                                  0.0
overlap_ratio_actual                                                  0.0
max_speakers                                                            2
snr_db                                                                7.4
noise_type                                                              T
overlap_mask_path                                                 no mask
source_files            [PosixPath('/home/jamin/Year3Proj/Data/LibriSp...
noise_files                     [PosixPath('Data/Noise/TMETRO/ch10.wav')]
Name: 101, dtype: object
[('dummy-speaker', 'It is believed he had been stabbed. So you think you want to be Victoria? It is not I who desire it. It is the Lord, replied Savonarola coldly. Impossible, impossible, murmured Lorenzo. Very well. Then die as you have lived, cried the monk in the midst of your courtiers and flatteries. Self control is a very good thing. It was not, however, without an inward fear, against which the praises of his friends availed nothing,')]
[('218', 'A LAMP COULD NOT HAVE EXPIRED WITH MORE AWFUL EFFECT CATHERINE FOR A FEW MOMENTS WAS MOTIONLESS WITH HORROR IT WAS DONE COMPLETELY NOT A REMNANT OF LIGHT IN THE WICK COULD GIVE HOPE TO THE REKINDLING BREATH DARKNESS IMPENETRABLE AND IMMOVABLE FILLED THE ROOM', 0.0, 15.675), ('28452', 'FOR WHICH SHE HAS A WHOLE HEARTFUL OF LOVE AND THE SIGHT OF WHICH IS BETTER TO HER THAN MEDICINE DURING THE MONTH OF JULY WE EAGERLY WATCHED THE INCOMING STEAMERS AND WELCOMED ALL NEW COMERS WHO LANDED IN CHINIK', 15.8714375, 31.8814375), ('218', 'ACKNOWLEDGED THAT IT WAS BY NO MEANS AN ILL SIZED ROOM AND FURTHER CONFESSED THAT THOUGH AS CARELESS ON SUCH SUBJECTS AS MOST PEOPLE HE DID LOOK UPON A TOLERABLY LARGE EATING ROOM AS ONE OF THE NECESSARIES OF LIFE HE SUPPOSED HOWEVER', 32.138, 45.203), ('28452', "AND WAS WATCHED WITH EAGER EYES BY EVERYONE WE ATE LETTUCE AND RADISHES PICKED FRESH FROM THE GARDEN BEDS WHERE THEY HAD BEEN SOWN BY THE CAPTAIN'S OWN HANDS AND WE FOUND AGEETUK AND MOLLIE TO BE QUITE FAMOUS COOKS", 45.5575625, 61.1225625)]
for which she has a whole heartful of love and the sight of which is better to her than medicine during the month of july we eagerly watched the incoming steamers and welcomed all new comers who landed in chinik and was watched with eager eyes by everyone we ate lettuce and radishes picked fresh from the garden beds where they had been sown by the captain's own hands and we found ageetuk and mollie to be quite famous cooks
a lamp could not have expired with more awful effect catherine for a few moments was motionless with horror it was done completely not a remnant of light in the wick could give hope to the rekindling breath darkness impenetrable and immovable filled the room acknowledged that it was by no means an ill sized room and further confessed that though as careless on such subjects as most people he did look upon a tolerably large eating room as one of the necessaries of life he supposed however

In [43]:
mrs_wer_beam_2chain(chain_a, chain_b, hyp, 32, 1.0, True, True)

{'distance': 196,
 'wer': 1.0,
 'n_ref': 196,
 'alignment': [('delete_a', 'A', 'it', None),
  ('delete_a', 'A', 'is', None),
  ('delete_a', 'A', 'not', None),
  ('delete_a', 'A', 'i', None),
  ('delete_a', 'A', 'who', None),
  ('delete_a', 'A', 'desire', None),
  ('delete_a', 'A', 'it', None),
  ('delete_a', 'A', 'it', None),
  ('delete_a', 'A', 'is', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'lord', None),
  ('delete_a', 'A', 'replied', None),
  ('delete_a', 'A', 'savonarola', None),
  ('delete_a', 'A', 'coldly', None),
  ('delete_a', 'A', 'impossible', None),
  ('delete_a', 'A', 'impossible', None),
  ('delete_a', 'A', 'murmured', None),
  ('delete_a', 'A', 'lorenzo', None),
  ('delete_a', 'A', 'very', None),
  ('delete_a', 'A', 'well', None),
  ('delete_a', 'A', 'then', None),
  ('delete_a', 'A', 'die', None),
  ('delete_a', 'A', 'as', None),
  ('delete_a', 'A', 'you', None),
  ('delete_a', 'A', 'have', None),
  ('delete_a', 'A', 'lived', None),
  ('delete_a', 'A', 'cried', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'monk', None),
  ('delete_a', 'A', 'in', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'midst', None),
  ('delete_a', 'A', 'of', None),
  ('delete_a', 'A', 'your', None),
  ('delete_a', 'A', 'courtiers', None),
  ('delete_a', 'A', 'and', None),
  ('delete_a', 'A', 'flatterers', None),
  ('delete_a', 'A', 'my', None),
  ('delete_a', 'A', 'father', None),
  ('delete_a', 'A', 'shall', None),
  ('delete_a', 'A', 'i', None),
  ('delete_a', 'A', 'have', None),
  ('delete_a', 'A', 'time', None),
  ('delete_a', 'A', 'asked', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'dying', None),
  ('delete_a', 'A', 'man', None),
  ('delete_a', 'A', 'god', None),
  ('delete_a', 'A', 'will', None),
  ('delete_a', 'A', 'give', None),
  ('delete_a', 'A', 'it', None),
  ('delete_a', 'A', 'to', None),
  ('delete_a', 'A', 'you', None),
  ('delete_a', 'A', 'replied', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'monk', None),
  ('delete_a', 'A', 'but', None),
  ('delete_a', 'A', 'a', None),
  ('delete_a', 'A', 'prophet', None),
  ('delete_a', 'A', 'yet', None),
  ('delete_a', 'A', 'although', None),
  ('delete_a', 'A', 'hitherto', None),
  ('delete_a', 'A', 'he', None),
  ('delete_a', 'A', 'had', None),
  ('delete_a', 'A', 'bowed', None),
  ('delete_a', 'A', 'his', None),
  ('delete_a', 'A', 'head', None),
  ('delete_a', 'A', 'before', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'authority', None),
  ('delete_a', 'A', 'of', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'church', None),
  ('delete_a', 'A', 'he', None),
  ('delete_a', 'A', 'had', None),
  ('delete_a', 'A', 'already', None),
  ('delete_a', 'A', 'raised', None),
  ('delete_a', 'A', 'it', None),
  ('delete_a', 'A', 'against', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'temporal', None),
  ('delete_a', 'A', 'power', None),
  ('delete_a', 'A', 'to', None),
  ('delete_a', 'A', 'him', None),
  ('delete_a', 'A', 'religion', None),
  ('delete_a', 'A', 'and', None),
  ('delete_a', 'A', 'liberty', None),
  ('delete_a', 'A', 'appeared', None),
  ('delete_a', 'A', 'as', None),
  ('delete_a', 'A', 'two', None),
  ('delete_a', 'A', 'virgins', None),
  ('delete_a', 'A', 'equally', None),
  ('delete_a', 'A', 'sacred', None),
  ('delete_a', 'A', 'in', None),
  ('delete_a', 'A', 'a', None),
  ('delete_a', 'A', 'man', None),
  ('delete_a', 'A', 'of', None),
  ('delete_a', 'A', 'less', None),
  ('delete_a', 'A', 'high', None),
  ('delete_a', 'A', 'place', None),
  ('delete_a', 'A', 'they', None),
  ('delete_a', 'A', 'might', None),
  ('delete_a', 'A', 'perhaps', None),
  ('delete_a', 'A', 'have', None),
  ('delete_a', 'A', 'been', None),
  ('delete_a', 'A', 'called', None),
  ('delete_a', 'A', 'crimes', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'dominican', None),
  ('delete_a', 'A', 'giralamo', None),
  ('delete_a', 'A', 'francesco', None),
  ('delete_a', 'A', 'savonarola', None),
  ('delete_a', 'A', 'it', None),
  ('delete_a', 'A', 'was', None),
  ('delete_a', 'A', 'not', None),
  ('delete_a', 'A', 'however', None),
  ('delete_a', 'A', 'without', None),
  ('delete_a', 'A', 'an', None),
  ('delete_a', 'A', 'inward', None),
  ('delete_a', 'A', 'fear', None),
  ('delete_a', 'A', 'against', None),
  ('delete_a', 'A', 'which', None),
  ('delete_a', 'A', 'the', None),
  ('delete_a', 'A', 'praises', None),
  ('delete_a', 'A', 'of', None),
  ('delete_a', 'A', 'his', None),
  ('delete_a', 'A', 'friends', None),
  ('delete_a', 'A', 'availed', None),
  ('delete_a', 'A', 'nothing', None),
  ('delete_b', 'B', 'it', None),
  ('delete_b', 'B', 'is', None),
  ('delete_b', 'B', 'believed', None),
  ('delete_b', 'B', 'he', None),
  ('delete_b', 'B', 'had', None),
  ('delete_b', 'B', 'been', None),
  ('delete_b', 'B', 'stabbed.', None),
  ('delete_b', 'B', 'so', None),
  ('delete_b', 'B', 'you', None),
  ('delete_b', 'B', 'think', None),
  ('delete_b', 'B', 'you', None),
  ('delete_b', 'B', 'want', None),
  ('delete_b', 'B', 'to', None),
  ('delete_b', 'B', 'be', None),
  ('delete_b', 'B', 'victoria?', None),
  ('delete_b', 'B', "it's", None),
  ('delete_b', 'B', 'hard', None),
  ('delete_b', 'B', 'not', None),
  ('delete_b', 'B', 'to.', None),
  ('delete_b', 'B', 'well,', None),
  ('delete_b', 'B', 'was', None),
  ('delete_b', 'B', 'it?', None),
  ('delete_b', 'B', 'subs', None),
  ('delete_b', 'B', 'not', None),
  ('delete_b', 'B', 'used,', None),
  ('delete_b', 'B', 'mcgraw.', None),
  ('delete_b', 'B', 'that', None),
  ('delete_b', 'B', 'is', None),
  ('delete_b', 'B', 'difficult', None),
  ('delete_b', 'B', 'to', None),
  ('delete_b', 'B', 'answer.', None),
  ('delete_b', 'B', "that'd", None),
  ('delete_b', 'B', 'be', None),
  ('delete_b', 'B', 'good', None),
  ('delete_b', 'B', 'for', None),
  ('delete_b', 'B', 'the', None),
  ('insert',
   'H',
   None,
   ('dummy-speaker',
    'It is believed he had been stabbed. So you think you want to be Victoria? It is not I who desire it. It is the Lord, replied Savonarola coldly. Impossible, impossible, murmured Lorenzo. Very well. Then die as you have lived, cried the monk in the midst of your courtiers and flatteries. Self control is a very good thing. It was not, however, without an inward fear, against which the praises of his friends availed nothing,')),
  ('delete_b', 'B', 'whole', None),
  ('delete_b', 'B', 'city.', None),
  ('delete_b', 'B', 'they', None),
  ('delete_b', 'B', 'finished', None),
  ('delete_b', 'B', 'second', None),
  ('delete_b', 'B', 'and', None),
  ('delete_b', 'B', 'third.', None),
  ('delete_b', 'B', 'they', None),
  ('delete_b', 'B', 'made', None),
  ('delete_b', 'B', 'it', None),
  ('delete_b', 'B', 'very', None),
  ('delete_b', 'B', 'difficult', None),
  ('delete_b', 'B', 'for', None),
  ('delete_b', 'B', 'us.', None),
  ('delete_b', 'B', 'there', None),
  ('delete_b', 'B', 'is', None),
  ('delete_b', 'B', 'no', None),
  ('delete_b', 'B', 'internal', None),
  ('delete_b', 'B', 'damage.', None),
  ('delete_b', 'B', 'self', None),
  ('delete_b', 'B', 'control', None),
  ('delete_b', 'B', 'is', None),
  ('delete_b', 'B', 'just', None),
  ('delete_b', 'B', 'one', None),
  ('delete_b', 'B', 'instalment.', None),
  ('delete_b', 'B', 'it', None),
  ('delete_b', 'B', 'may', None),
  ('delete_b', 'B', 'also', None),
  ('delete_b', 'B', 'be', None),
  ('delete_b', 'B', 'her', None),
  ('delete_b', 'B', 'last.', None)]}

In [ ]:
# extract row whose transcript contains ("any speaker", None) or ("any speaker", "None") or ("any speaker", np.nan) where transcript is a list of tuples (speaker, transcript)
row_none = metas[metas["transcript"].apply(lambda x: any((t[0] == "any speaker" and (t[1] is None or t[1] == "None" or (isinstance(t[1], float) and np.isnan(t[1]))) for t in eval(x))))]

In [ ]:
row_none

Empty DataFrame
Columns: [clip_id, audio_path, transcript, overlap_ratio_target, overlap_ratio_actual, max_speakers, snr_db, noise_type, overlap_mask_path, source_files, noise_files]
Index: []

In [ ]:
import os
print(os.environ.get("LD_LIBRARY_PATH"))

/home/jamin/mambaforge/envs/fw311/lib/python3.11/site-packages/nvidia/cublas/lib:/home/jamin/mambaforge/envs/fw311/lib/python3.11/site-packages/nvidia/cudnn/lib:

In [ ]:
import ctypes
ctypes.CDLL("libcublas.so.12")
ctypes.CDLL("libcudnn.so.9")
print("CUDA libs load OK")

CUDA libs load OK

In [ ]:
def load_mixture_meta(path: Path) -> pd.DataFrame:
    return pd.read_csv(path)
def load_mixture_audio(path: Path, sr: int = 16000) -> Tuple[np.ndarray, int]:
    audio, sr = librosa.load(path, sr=sr)
    return audio, sr

In [ ]:
meta_df = load_mixture_meta(Path(os.pardir,"Output", "manifest.csv"))

In [ ]:
meta_df.clip_id.filter

<bound method NDFrame.filter of 0       mix_0.00_2_None_D_0000000
1       mix_0.00_2_None_P_0000001
2       mix_0.00_2_None_T_0000002
3        mix_0.00_2_7.4_D_0000003
4        mix_0.00_2_7.4_P_0000004
                  ...
3715       mix_0.40_2_0_P_0003715
3716       mix_0.40_2_0_T_0003716
3717      mix_0.40_2_-5_D_0003717
3718      mix_0.40_2_-5_P_0003718
3719      mix_0.40_2_-5_T_0003719
Name: clip_id, Length: 3720, dtype: str>

In [ ]:
# filter out clip ids that starts with mix_0.14
test_meta = meta_df[meta_df.clip_id.str.startswith("mix_0.14_2_None_D_0000144")].head(1)
test_meta

,clip_id,audio_path,transcript,overlap_ratio_target,overlap_ratio_actual,max_speakers,snr_db,noise_type,overlap_mask_path,source_files,noise_files
144,mix_0.14_2_None_D_0000144,Output/audio/mix_0.14_2_None_D_0000144.wav,"[('125-121342-0038', ""THEY DON'T THEY JUST WAN...",0.14,0.14,2,NaN,D,Output/masks/mix_0.14_2_None_D_0000144.npy,[PosixPath('/home/jamin/Year3Proj/Data/LibriSp...,[]

In [ ]:
print(test_meta.audio_path.values[0])
print(Path(os.pardir, test_meta.audio_path.values[0]))

Output/audio/mix_0.14_2_None_D_0000144.wav
../Output/audio/mix_0.14_2_None_D_0000144.wav

In [ ]:
# model = WhisperModel("large-v3", device="cuda")

# segments, info = model.transcribe(Path(os.pardir, test_meta.audio_path.values[0]))
# for segment in segments:
#     print("[%.2fs -> %.2fs] %s" % (segment.start, segment.end, segment.text))

In [ ]:
# import torch
# from transformers import pipeline

# device = 0 if torch.cuda.is_available() else -1

# asr = pipeline(
#     "automatic-speech-recognition",
#     model="facebook/wav2vec2-large-960h",
#     device=0,
# )
# audio = load_mixture_audio(Path(os.pardir, test_meta.audio_path.values[0]))[0]
# result = asr(audio)
# print(result["text"])

In [ ]:
# from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
# import torch

# # load model and processor
# processor = Wav2Vec2Processor.from_pretrained("facebook/wav2vec2-large-960h")
# model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-large-960h")
    
# # load dummy dataset and read soundfiles
# audio = load_mixture_audio(Path(os.pardir, test_meta.audio_path.values[0]))[0]

# # tokenize
# input_values = processor(audio, return_tensors="pt", padding="longest").input_values  # Batch size 1

# # retrieve logits
# logits = model(input_values).logits

# # take argmax and decode
# predicted_ids = torch.argmax(logits, dim=-1)
# transcription = processor.batch_decode(predicted_ids)

In [ ]:
# print(test_meta.transcript.values[0].astype(str))

# print(" ".join(seg[1] for seg in test_meta.transcript.values[0]))

In [ ]:
# import nemo.collections.asr as nemo_asr
# asr_model = nemo_asr.models.ASRModel.from_pretrained(model_name="nvidia/parakeet-tdt-0.6b-v3")
# output = asr_model.transcribe([Path(os.pardir, test_meta.audio_path.values[0])])
# print(output[0].text)

In [ ]:
# import whisperx
# device = "cuda"   # or "cpu"
# batch_size = 1
# compute_type = "int8"
# model = whisperx.load_model("large-v2", device, compute_type=compute_type)
# audio = whisperx.load_audio(Path(os.pardir) / test_meta.audio_path.values[0])

# result = model.transcribe(audio, batch_size=batch_size)

In [ ]:
# import nemo.collections.asr as nemo_asr
# asr_model = nemo_asr.models.ASRModel.from_pretrained("nvidia/parakeet-tdt-0.6b-v2")
# transcript = asr_model.transcribe([test_meta.audio_path.values[0]])

[NeMo W 2026-04-04 00:15:05 megatron_init:62] Megatron num_microbatches_calculator not found, using Apex version.
OneLogger: Setting error_handling_strategy to DISABLE_QUIETLY_AND_REPORT_METRIC_ERROR for rank (rank=0) with OneLogger disabled. To override: explicitly set error_handling_strategy parameter.
No exporters were provided. This means that no telemetry data will be collected.
Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [ ]:
import pickle
with open("funasr_output.pkl", "rb") as f:
    funasr_output = pickle.load(f)

In [ ]:
funasr_output[0][0]

{'key': 'rand_key_1t9EwL56nGisi',
 'text': "They don't. They just want the fun of eating it all over again. The matron doesn't want to repeat her own feelings, but she's just a part of the world. Again, Ventnor's rifle cracked. One of the colors of the world is down, another's down, more did he reproach himself for feelings that were bound to the horseman, but his sworn foot soldiers, a forest of shining planks above them, clearly to us came their battle cries. Again, Ventnor's rifle cracked. I detest poor people. I hate them for being poor. Poverty may have been beautiful for the horseman, but it's one foot in a forest and truly a big faint radiance. It was her eyes, her great wide eyes whose clear form magnified us. Over us whined the bullets from the covering guns. The fathom deeper by lie, with old desires restrained before. No, I heard a song. The matron doesn't want to repeat her. We just want to repeat her honeymoon. How the smell of it suddenly cleared the air and threw everyone in the residence. If we could but reach it, the darting snake streamed red.",
 'text_tn': 'They dont They just want the fun of eating it all over again The matron doesnt want to repeat her own feelings but shes just a part of the world Again Ventnors rifle cracked One of the colors of the world is down anothers down more did he reproach himself for feelings that were bound to the horseman but his sworn foot soldiers a forest of shining planks above them clearly to us came their battle cries Again Ventnors rifle cracked I detest poor people I hate them for being poor Poverty may have been beautiful for the horseman but its one foot in a forest and truly a big faint radiance It was her eyes her great wide eyes whose clear form magnified us Over us whined the bullets from the covering guns The fathom deeper by lie with old desires restrained before No I heard a song The matron doesnt want to repeat her We just want to repeat her honeymoon How the smell of it suddenly cleared the air and threw everyone in the residence If we could but reach it the darting snake streamed red',
 'label': 'null',
 'ctc_text': "they don't they just want the fun of eating it all over again the mat doesn't want to repeat her girlhood she wants to repeat her own tastes the best isabel cl ros el were all american would pitch probably south ros was out wonderful hit ever the first based from it and ever was swift than te at heels from length the dart red't over again the't't want to her girlfriendhood she wants to repeat her honeymoon how the smell of it has suddenly cleared the air and given everyone in the car a moment glow i poor people thought am suddenly i hate them for being poor poverty may have been beautiful the horse soldiers a forest of shining points and dul gleaming pe above them clearly to us came their battle cries again vent's rifle one of the foremost went down more he rep himself for feelings that were natural and and sincere he all his reactions as a part of himchangingoral this problem of poverty transformed magn over mine the close were to the fisher we couldn but close the arrows none more virtue to lose just as a cooling pot gives off heat so all through youth and ad we give off of virtue that's what's called genius mis interesting idea flames no nor that through her ve her body gle faint rad it was her eyes her great wide eyes whose clear depths were like pools lie oldrainedined to clam lifeward with a cry as dark flies out the grain door and so in quest of cre to share i seek assert day again",
 'ctc_timestamps': [{'token': 'they',
   'start_time': 0.24,
   'end_time': 0.3,
   'score': 0.45},
  {'token': ' don', 'start_time': 0.42, 'end_time': 0.48, 'score': 0.729},
  {'token': "'t", 'start_time': 0.54, 'end_time': 0.66, 'score': 0.781},
  {'token': ' they', 'start_time': 1.2, 'end_time': 1.26, 'score': 0.862},
  {'token': ' just', 'start_time': 1.44, 'end_time': 1.5, 'score': 0.98},
  {'token': ' want', 'start_time': 1.62, 'end_time': 1.68, 'score': 0.973},
  {'token': ' the', 'start_time': 1.8, 'end_time': 1.86, 'score': 0.888},
  {'token': ' fun', 'start_time': 1.86, 'end_time': 1.98, 'score': 0.799},
  {'token': ' of', 'start_time': 2.04, 'end_time': 2.1, 'score': 0.977},
  {'token': ' eating', 'start_time': 2.22, 'end_time': 2.28, 'score': 0.977},
  {'token': ' it', 'start_time': 2.46, 'end_time': 2.52, 'score': 0.961},
  {'token': ' all', 'start_time': 2.64, 'end_time': 2.7, 'score': 0.996},
  {'token': ' over', 'start_time': 2.82, 'end_time': 2.88, 'score': 0.991},
  {'token': ' again', 'start_time': 3.18, 'end_time': 3.24, 'score': 0.983},
  {'token': ' the', 'start_time': 4.26, 'end_time': 4.32, 'score': 0.907},
  {'token': ' mat', 'start_time': 4.38, 'end_time': 4.44, 'score': 0.215},
  {'token': ' doesn', 'start_time': 4.8, 'end_time': 4.86, 'score': 0.828},
  {'token': "'t", 'start_time': 4.86, 'end_time': 4.98, 'score': 0.955},
  {'token': ' want', 'start_time': 5.1, 'end_time': 5.16, 'score': 0.647},
  {'token': ' to', 'start_time': 5.22, 'end_time': 5.28, 'score': 0.917},
  {'token': ' repeat', 'start_time': 5.4, 'end_time': 5.52, 'score': 0.914},
  {'token': ' her', 'start_time': 5.7, 'end_time': 5.76, 'score': 0.996},
  {'token': ' girl', 'start_time': 5.82, 'end_time': 5.88, 'score': 0.688},
  {'token': 'hood', 'start_time': 6.12, 'end_time': 6.18, 'score': 0.791},
  {'token': ' she', 'start_time': 6.72, 'end_time': 6.78, 'score': 0.836},
  {'token': ' wants', 'start_time': 6.9, 'end_time': 6.96, 'score': 0.985},
  {'token': ' to', 'start_time': 7.08, 'end_time': 7.14, 'score': 0.956},
  {'token': ' repeat', 'start_time': 7.26, 'end_time': 7.38, 'score': 0.84},
  {'token': ' her', 'start_time': 7.56, 'end_time': 7.62, 'score': 0.994},
  {'token': ' own', 'start_time': 9.36, 'end_time': 9.42, 'score': 0.59},
  {'token': ' tastes', 'start_time': 9.66, 'end_time': 9.72, 'score': 0.296},
  {'token': ' the', 'start_time': 9.96, 'end_time': 10.02, 'score': 0.776},
  {'token': ' best', 'start_time': 10.14, 'end_time': 10.2, 'score': 0.781},
  {'token': ' is', 'start_time': 10.74, 'end_time': 10.8, 'score': 0.412},
  {'token': 'abel', 'start_time': 10.98, 'end_time': 11.04, 'score': 0.71},
  {'token': ' cl', 'start_time': 11.4, 'end_time': 11.46, 'score': 0.611},
  {'token': ' ros', 'start_time': 12.0, 'end_time': 12.06, 'score': 0.622},
  {'token': ' el', 'start_time': 12.6, 'end_time': 12.66, 'score': 0.47},
  {'token': ' were', 'start_time': 13.2, 'end_time': 13.26, 'score': 0.922},
  {'token': ' all', 'start_time': 13.44, 'end_time': 13.5, 'score': 0.864},
  {'token': ' american',
   'start_time': 13.74,
   'end_time': 13.8,
   'score': 0.565},
  {'token': ' would', 'start_time': 15.42, 'end_time': 15.48, 'score': 0.562},
  {'token': ' pitch', 'start_time': 15.6, 'end_time': 15.66, 'score': 0.792},
  {'token': ' probably',
   'start_time': 15.9,
   'end_time': 15.96,
   'score': 0.884},
  {'token': ' south', 'start_time': 16.38, 'end_time': 16.44, 'score': 0.986},
  {'token': ' ros', 'start_time': 17.46, 'end_time': 17.52, 'score': 0.735},
  {'token': ' was', 'start_time': 17.94, 'end_time': 18.0, 'score': 0.931},
  {'token': ' out', 'start_time': 18.18, 'end_time': 18.24, 'score': 0.982},
  {'token': ' wonderful',
   'start_time': 18.9,
   'end_time': 18.96,
   'score': 0.467},
  {'token': ' hit', 'start_time': 19.38, 'end_time': 19.44, 'score': 0.9},
  {'token': ' ever', 'start_time': 19.86, 'end_time': 19.92, 'score': 0.825},
  {'token': ' the', 'start_time': 20.16, 'end_time': 20.22, 'score': 0.749},
  {'token': ' first', 'start_time': 20.7, 'end_time': 20.76, 'score': 0.727},
  {'token': ' based', 'start_time': 21.0, 'end_time': 21.06, 'score': 0.394},
  {'token': ' from', 'start_time': 21.54, 'end_time': 21.6, 'score': 0.812},
  {'token': ' it', 'start_time': 21.72, 'end_time': 21.78, 'score': 0.646},
  {'token': ' and', 'start_time': 22.44, 'end_time': 22.56, 'score': 0.765},
  {'token': ' ever', 'start_time': 22.68, 'end_time': 22.74, 'score': 0.804},
  {'token': ' was', 'start_time': 23.04, 'end_time': 23.1, 'score': 0.555},
  {'token': ' swift', 'start_time': 23.4, 'end_time': 23.46, 'score': 0.587},
  {'token': ' than', 'start_time': 23.76, 'end_time': 23.82, 'score': 0.555},
  {'token': ' te', 'start_time': 24.6, 'end_time': 24.66, 'score': 0.683},
  {'token': ' at', 'start_time': 25.08, 'end_time': 25.14, 'score': 0.51},
  {'token': ' heels', 'start_time': 25.44, 'end_time': 25.5, 'score': 0.637},
  {'token': ' from', 'start_time': 28.02, 'end_time': 28.08, 'score': 0.523},
  {'token': ' length', 'start_time': 28.8, 'end_time': 28.86, 'score': 0.64},
  {'token': ' the', 'start_time': 29.22, 'end_time': 29.28, 'score': 0.67},
  {'token': ' dart', 'start_time': 29.46, 'end_time': 29.52, 'score': 0.848},
  {'token': ' red', 'start_time': 30.96, 'end_time': 31.02, 'score': 0.598},
  {'token': "'t", 'start_time': 32.4, 'end_time': 32.46, 'score': 0.67},
  {'token': ' over', 'start_time': 34.74, 'end_time': 34.8, 'score': 0.564},
  {'token': ' again', 'start_time': 35.1, 'end_time': 35.16, 'score': 0.568},
  {'token': ' the', 'start_time': 36.18, 'end_time': 36.24, 'score': 0.558},
  {'token': "'t", 'start_time': 36.66, 'end_time': 36.72, 'score': 0.302},
  {'token': "'t", 'start_time': 36.78, 'end_time': 36.84, 'score': 0.836},
  {'token': ' want', 'start_time': 36.96, 'end_time': 37.02, 'score': 0.468},
  {'token': ' to', 'start_time': 37.14, 'end_time': 37.2, 'score': 0.629},
  {'token': ' her', 'start_time': 37.62, 'end_time': 37.68, 'score': 0.99},
  {'token': ' girlfriend',
   'start_time': 37.74,
   'end_time': 37.8,
   'score': 0.477},
  {'token': 'hood', 'start_time': 38.04, 'end_time': 38.1, 'score': 0.716},
  {'token': ' she', 'start_time': 38.64, 'end_time': 38.7, 'score': 0.694},
  {'token': ' wants', 'start_time': 38.76, 'end_time': 38.82, 'score': 0.95},
  {'token': ' to', 'start_time': 39.0, 'end_time': 39.06, 'score': 0.852},
  {'token': ' repeat', 'start_time': 39.18, 'end_time': 39.24, 'score': 0.955},
  {'token': ' her', 'start_time': 39.48, 'end_time': 39.54, 'score': 0.996},
  {'token': ' honeymoon',
   'start_time': 39.6,
   'end_time': 39.72,
   'score': 0.812},
  {'token': ' how', 'start_time': 40.62, 'end_time': 40.68, 'score': 0.98},
  {'token': ' the', 'start_time': 40.86, 'end_time': 40.92, 'score': 0.979},
  {'token': ' smell', 'start_time': 41.04, 'end_time': 41.1, 'score': 0.986},
  {'token': ' of', 'start_time': 41.22, 'end_time': 41.28, 'score': 0.819},
  {'token': ' it', 'start_time': 41.34, 'end_time': 41.4, 'score': 0.975},
  {'token': ' has', 'start_time': 41.58, 'end_time': 41.64, 'score': 0.516},
  {'token': ' suddenly',
   'start_time': 41.82,
   'end_time': 41.88,
   'score': 0.82},
  {'token': ' cleared', 'start_time': 42.3, 'end_time': 42.36, 'score': 0.96},
  {'token': ' the', 'start_time': 42.6, 'end_time': 42.66, 'score': 0.721},
  {'token': ' air', 'start_time': 42.72, 'end_time': 42.84, 'score': 0.897},
  {'token': ' and', 'start_time': 42.96, 'end_time': 43.02, 'score': 0.951},
  {'token': ' given', 'start_time': 43.14, 'end_time': 43.2, 'score': 0.682},
  {'token': ' everyone',
   'start_time': 43.5,
   'end_time': 43.56,
   'score': 0.936},
  {'token': ' in', 'start_time': 43.8, 'end_time': 43.86, 'score': 0.87},
  {'token': ' the', 'start_time': 43.92, 'end_time': 43.98, 'score': 0.813},
  {'token': ' car', 'start_time': 44.1, 'end_time': 44.16, 'score': 0.968},
  {'token': ' a', 'start_time': 44.52, 'end_time': 44.58, 'score': 0.731},
  {'token': ' moment', 'start_time': 44.7, 'end_time': 44.76, 'score': 0.62},
  {'token': ' glow', 'start_time': 45.36, 'end_time': 45.42, 'score': 0.797},
  {'token': ' i', 'start_time': 46.86, 'end_time': 46.92, 'score': 0.896},
  {'token': ' poor', 'start_time': 47.58, 'end_time': 47.7, 'score': 0.937},
  {'token': ' people', 'start_time': 47.82, 'end_time': 47.94, 'score': 0.994},
  {'token': ' thought',
   'start_time': 48.36,
   'end_time': 48.42,
   'score': 0.818},
  {'token': ' am', 'start_time': 48.6, 'end_time': 48.66, 'score': 0.68},
  {'token': ' suddenly',
   'start_time': 49.08,
   'end_time': 49.14,
   'score': 0.608},
  {'token': ' i', 'start_time': 50.1, 'end_time': 50.16, 'score': 0.903},
  {'token': ' hate', 'start_time': 50.28, 'end_time': 50.34, 'score': 0.943},
  {'token': ' them', 'start_time': 50.52, 'end_time': 50.58, 'score': 0.851},
  {'token': ' for', 'start_time': 50.7, 'end_time': 50.76, 'score': 0.78},
  {'token': ' being', 'start_time': 50.82, 'end_time': 50.88, 'score': 0.91},
  {'token': ' poor', 'start_time': 51.12, 'end_time': 51.18, 'score': 0.847},
  {'token': ' poverty',
   'start_time': 51.96,
   'end_time': 52.02,
   'score': 0.973},
  {'token': ' may', 'start_time': 52.44, 'end_time': 52.5, 'score': 0.972},
  {'token': ' have', 'start_time': 52.56, 'end_time': 52.62, 'score': 0.539},
  {'token': ' been', 'start_time': 52.74, 'end_time': 52.8, 'score': 0.937},
  {'token': ' beautiful',
   'start_time': 52.92,
   'end_time': 52.98,
   'score': 0.579},
  {'token': ' the', 'start_time': 53.46, 'end_time': 53.52, 'score': 0.596},
  {'token': ' horse', 'start_time': 53.58, 'end_time': 53.64, 'score': 0.487},
  {'token': ' soldiers',
   'start_time': 54.72,
   'end_time': 54.78,
   'score': 0.442},
  {'token': ' a', 'start_time': 55.2, 'end_time': 55.26, 'score': 0.449},
  {'token': ' forest', 'start_time': 55.32, 'end_time': 55.38, 'score': 0.732},
  {'token': ' of', 'start_time': 55.74, 'end_time': 55.8, 'score': 0.716},
  {'token': ' shining', 'start_time': 56.1, 'end_time': 56.16, 'score': 0.449},
  {'token': ' points', 'start_time': 56.52, 'end_time': 56.58, 'score': 0.699},
  {'token': ' and', 'start_time': 56.94, 'end_time': 57.0, 'score': 0.786},
  {'token': ' dul', 'start_time': 57.12, 'end_time': 57.18, 'score': 0.163},
  {'token': ' gle', 'start_time': 57.54, 'end_time': 57.6, 'score': 0.879},
  {'token': 'aming', 'start_time': 57.72, 'end_time': 57.78, 'score': 0.516},
  {'token': ' pe', 'start_time': 57.96, 'end_time': 58.02, 'score': 0.285},
  {'token': ' above', 'start_time': 58.32, 'end_time': 58.38, 'score': 0.947},
  {'token': ' them', 'start_time': 58.56, 'end_time': 58.62, 'score': 0.983},
  {'token': ' clearly',
   'start_time': 59.28,
   'end_time': 59.34,
   'score': 0.874},
  {'token': ' to', 'start_time': 59.76, 'end_time': 59.82, 'score': 0.851},
  {'token': ' us', 'start_time': 59.88, 'end_time': 59.94, 'score': 0.547},
  {'token': ' came', 'start_time': 60.18, 'end_time': 60.24, 'score': 0.909},
  {'token': ' their', 'start_time': 60.48, 'end_time': 60.54, 'score': 0.798},
  {'token': ' battle', 'start_time': 60.66, 'end_time': 60.72, 'score': 0.919},
  {'token': ' cries', 'start_time': 61.08, 'end_time': 61.14, 'score': 0.696},
  {'token': ' again', 'start_time': 62.4, 'end_time': 62.46, 'score': 0.975},
  {'token': ' vent', 'start_time': 62.76, 'end_time': 62.82, 'score': 0.54},
  {'token': "'s", 'start_time': 63.0, 'end_time': 63.12, 'score': 0.581},
  {'token': ' rifle', 'start_time': 63.24, 'end_time': 63.3, 'score': 0.794},
  {'token': ' one', 'start_time': 64.56, 'end_time': 64.62, 'score': 0.799},
  {'token': ' of', 'start_time': 64.68, 'end_time': 64.74, 'score': 0.762},
  {'token': ' the', 'start_time': 64.74, 'end_time': 64.8, 'score': 0.8},
  {'token': ' foremost',
   'start_time': 64.92,
   'end_time': 64.98,
   'score': 0.833},
  {'token': ' went', 'start_time': 65.88, 'end_time': 65.94, 'score': 0.704},
  {'token': ' down', 'start_time': 66.18, 'end_time': 66.24, 'score': 0.905},
  {'token': ' more', 'start_time': 67.56, 'end_time': 67.62, 'score': 0.364},
  {'token': ' he', 'start_time': 67.98, 'end_time': 68.04, 'score': 0.694},
  {'token': ' rep', 'start_time': 68.16, 'end_time': 68.22, 'score': 0.794},
  {'token': ' himself',
   'start_time': 68.58,
   'end_time': 68.64,
   'score': 0.893},
  {'token': ' for', 'start_time': 68.94, 'end_time': 69.0, 'score': 0.582},
  {'token': ' feelings',
   'start_time': 69.12,
   'end_time': 69.18,
   'score': 0.873},
  {'token': ' that', 'start_time': 69.48, 'end_time': 69.54, 'score': 0.964},
  {'token': ' were', 'start_time': 69.6, 'end_time': 69.72, 'score': 0.874},
  {'token': ' natural', 'start_time': 69.84, 'end_time': 69.9, 'score': 0.981},
  {'token': ' and', 'start_time': 70.2, 'end_time': 70.26, 'score': 0.975},
  {'token': ' and', 'start_time': 70.32, 'end_time': 70.38, 'score': 0.529},
  {'token': ' sincere',
   'start_time': 70.56,
   'end_time': 70.62,
   'score': 0.334},
  {'token': ' he', 'start_time': 71.64, 'end_time': 71.7, 'score': 0.904},
  {'token': ' all', 'start_time': 72.24, 'end_time': 72.3, 'score': 0.961},
  {'token': ' his', 'start_time': 72.42, 'end_time': 72.48, 'score': 0.968},
  {'token': ' reactions',
   'start_time': 72.66,
   'end_time': 72.72,
   'score': 0.659},
  {'token': ' as', 'start_time': 73.08, 'end_time': 73.14, 'score': 0.741},
  {'token': ' a', 'start_time': 73.26, 'end_time': 73.32, 'score': 0.864},
  {'token': ' part', 'start_time': 73.38, 'end_time': 73.44, 'score': 0.997},
  {'token': ' of', 'start_time': 73.56, 'end_time': 73.62, 'score': 0.896},
  {'token': ' him', 'start_time': 73.68, 'end_time': 73.74, 'score': 0.813},
  {'token': 'changing',
   'start_time': 74.28,
   'end_time': 74.34,
   'score': 0.596},
  {'token': 'oral', 'start_time': 75.12, 'end_time': 75.18, 'score': 0.547},
  {'token': ' this', 'start_time': 76.38, 'end_time': 76.44, 'score': 0.946},
  {'token': ' problem',
   'start_time': 76.68,
   'end_time': 76.74,
   'score': 0.979},
  {'token': ' of', 'start_time': 76.98, 'end_time': 77.04, 'score': 0.737},
  {'token': ' poverty',
   'start_time': 77.22,
   'end_time': 77.28,
   'score': 0.902},
  {'token': ' transformed',
   'start_time': 77.82,
   'end_time': 77.88,
   'score': 0.869},
  {'token': ' magn', 'start_time': 78.48, 'end_time': 78.54, 'score': 0.918},
  {'token': ' over', 'start_time': 79.02, 'end_time': 79.08, 'score': 0.714},
  {'token': ' mine', 'start_time': 79.44, 'end_time': 79.5, 'score': 0.203},
  {'token': ' the', 'start_time': 79.74, 'end_time': 79.8, 'score': 0.544},
  {'token': ' close', 'start_time': 81.96, 'end_time': 82.02, 'score': 0.474},
  {'token': ' were', 'start_time': 82.32, 'end_time': 82.38, 'score': 0.523},
  {'token': ' to', 'start_time': 82.92, 'end_time': 82.98, 'score': 0.678},
  {'token': ' the', 'start_time': 83.04, 'end_time': 83.1, 'score': 0.525},
  {'token': ' fisher', 'start_time': 83.58, 'end_time': 83.64, 'score': 0.659},
  {'token': ' we', 'start_time': 84.6, 'end_time': 84.66, 'score': 0.539},
  {'token': ' couldn', 'start_time': 84.72, 'end_time': 84.78, 'score': 0.397},
  {'token': ' but', 'start_time': 84.96, 'end_time': 85.02, 'score': 0.547},
  {'token': ' close', 'start_time': 85.92, 'end_time': 85.98, 'score': 0.386},
  {'token': ' the', 'start_time': 88.2, 'end_time': 88.26, 'score': 0.818},
  {'token': ' arrows', 'start_time': 88.32, 'end_time': 88.44, 'score': 0.668},
  {'token': ' none', 'start_time': 89.76, 'end_time': 89.82, 'score': 0.631},
  {'token': ' more', 'start_time': 91.02, 'end_time': 91.08, 'score': 0.717},
  {'token': ' virtue', 'start_time': 91.26, 'end_time': 91.32, 'score': 0.439},
  {'token': ' to', 'start_time': 91.56, 'end_time': 91.62, 'score': 0.746},
  {'token': ' lose', 'start_time': 91.74, 'end_time': 91.8, 'score': 0.861},
  {'token': ' just', 'start_time': 92.76, 'end_time': 92.88, 'score': 0.869},
  {'token': ' as', 'start_time': 93.0, 'end_time': 93.06, 'score': 0.798},
  {'token': ' a', 'start_time': 93.12, 'end_time': 93.18, 'score': 0.489},
  {'token': ' cooling', 'start_time': 93.24, 'end_time': 93.3, 'score': 0.903},
  {'token': ' pot', 'start_time': 93.54, 'end_time': 93.6, 'score': 0.814},
  {'token': ' gives', 'start_time': 93.84, 'end_time': 93.9, 'score': 0.818},
  {'token': ' off', 'start_time': 94.02, 'end_time': 94.08, 'score': 0.995},
  {'token': ' heat', 'start_time': 94.26, 'end_time': 94.32, 'score': 0.973},